### ISSUE TITLE
Error merging annotations when ending the event

### ISSUE THREAD

**Issue by olmoch** [vmware-tanzu/observability-event-resource#9]
Hello! We are having an issue updating the severity annotation. We have essentially the following pipeline, configured to start an event when the job starts running and end it after an upgrade with Helm:
```
jobs:
- name: deploy
  plan:
  - in_parallel:
      steps:
      - put: observability
        params:
          action: start
          event_name: Deployment started
          annotations:
            severity: INFO
      - get: configuration
        trigger: true
  - params:
      chart: application-chart
      values: configuration/values.yaml
    put: helm-qapter-vi-dev
    on_success:
      put: observability
      params:
        action: end
        event: observability
        annotations:
          severity: SUCCESS
```

We want to modify the severity after the Helm process is finished (to set it to _SUCCESS_ or _WARN_ depending on the `on_success` or `on_failure`, for example). But when it runs it returns
```
2022/02/07 11:57:43 could not complete API call: error merging new annotations with existing annotations: could not retrieve required annotations field: /response/annotations at part 0: couldn't find key "response"
```

Looking at the code, it seems it is [reading the `/response/annotations` path](https://github.com/vmware-tanzu/observability-event-resource/blob/main/wavefront/events.go#L215) of the event, which makes sense for an [http response of this type](https://github.com/vmware-tanzu/observability-event-resource/blob/main/wavefront/events_test.go#L73), but in this case the event.json is being read [directly from the file](https://github.com/vmware-tanzu/observability-event-resource/blob/3686e152762ef3f718aae68586dcb2b6a8586944/out/command.go#L91) saved by the `in` step, which already [saves only the response](https://github.com/vmware-tanzu/observability-event-resource/blob/3686e152762ef3f718aae68586dcb2b6a8586944/wavefront/events.go#L160) from the body. Therefore it looks like there is an extra `/response` that is causing the error to appear.

Could someone take a look at this? It seems that removing the additional `/response` could be enough to solve it, but I'm not sure if this could break something else, and I don't know enough Go to redo the tests that could break. Thanks!
